version: '3.8'

services:
    postgres:
        container_name: postgres_container
        image: postgres:15
        environment:
            POSTGRES_DB: students_db
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-314159}
        ports:
            - '5433:5432'
        volumes:
            - postgres:/var/lib/postgresql/data
        restart: unless-stopped
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user@gmail.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
        ports:
            - '5050:80'
        restart: unless-stopped


volumes:
    postgres:

