version: '3.8'

services:
    application:
        image: mamyshevhen/student-ms
        environment:
            DATASOURCE_URL: ${DATASOURCE_URL:-jdbc:postgresql://postgres:5432/students_db}
            DATASOURCE_USERNAME: ${DATASOURCE_USERNAME:-postgres}
            DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD:-314159}
        ports:
            - '8080:8080'
    postgres:
        container_name: postgres_container
        image: postgres:15
        environment:
            POSTGRES_DB: students_db
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-314159}
        volumes:
            - postgres:/var/lib/postgresql/data
        restart: unless-stopped
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user@gmail.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
        ports:
            - '5050:80'
        restart: unless-stopped

volumes:
    postgres:
