version: '3.8'
services:
    postgres:
        image: postgres:15
        environment:
            - POSTGRES_DB=students_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=314159
        ports:
            - '5433:5432'
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
