spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/students_db
    username: postgres
    password: 314159

  flyway:
    baseline-on-migrate: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    log-request-details: true
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
#     view:
#       prefix: classpath:/templates
#       suffix: .html

#   thymeleaf:
#     prefix: classpath:/templates
#     suffix: .html
