--START--
--DROP DATABASE IF EXISTS students_db;
--CREATE DATABASE students_db;
CREATE TABLE students (student_id SERIAL, group_id INT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name  VARCHAR(255) NOT NULL, PRIMARY KEY (student_id));
CREATE TABLE groups (group_id   SERIAL, group_name VARCHAR(255) NOT NULL, PRIMARY KEY (group_id));
CREATE TABLE courses (course_id SERIAL, course_name VARCHAR(255) NOT NULL, course_description VARCHAR(255) NOT NULL, PRIMARY KEY (course_id) );
CREATE TABLE students_courses (student_id INT NOT NULL, course_id  INT NOT NULL, PRIMARY KEY (student_id, course_id), FOREIGN KEY (student_id) REFERENCES students (student_id), FOREIGN KEY (course_id) REFERENCES courses (course_id));
INSERT INTO groups (group_name) VALUES ('JV-1');
INSERT INTO groups (group_name) VALUES ('JV-2');
INSERT INTO groups (group_name) VALUES ('JV-3');
INSERT INTO groups (group_name) VALUES ('JV-4');
INSERT INTO groups (group_name) VALUES ('JV-5');
INSERT INTO groups (group_name) VALUES ('JV-6');
INSERT INTO groups (group_name) VALUES ('JV-7');
INSERT INTO groups (group_name) VALUES ('JV-8');
INSERT INTO groups (group_name) VALUES ('JV-9');
INSERT INTO groups (group_name) VALUES ('JV-10');
INSERT INTO courses (course_name, course_description) VALUES ('Java', 'Java programming language');
INSERT INTO courses (course_name, course_description) VALUES ('C#', 'C# programming language');
INSERT INTO courses (course_name, course_description) VALUES ('C++', 'C++ programming language');
INSERT INTO courses (course_name, course_description) VALUES ('Python', 'Python programming language');
INSERT INTO courses (course_name, course_description) VALUES ('JavaScript', 'JavaScript programming language');
INSERT INTO courses (course_name, course_description) VALUES ('PHP', 'PHP programming language');
INSERT INTO courses (course_name, course_description) VALUES ('HTML', 'HTML programming language');
INSERT INTO courses (course_name, course_description) VALUES ('CSS', 'CSS programming language');
INSERT INTO courses (course_name, course_description) VALUES ('SQL', 'SQL programming language');
INSERT INTO courses (course_name, course_description) VALUES ('Ruby', 'Ruby programming language');
INSERT INTO courses (course_name, course_description) VALUES ('Swift', 'Swift programming language');
INSERT INTO courses (course_name, course_description) VALUES ('Kotlin', 'Kotlin programming language');
INSERT INTO courses (course_name, course_description) VALUES ('Go', 'Go programming language');
INSERT INTO courses (course_name, course_description) VALUES ('Rust', 'Rust programming language');
INSERT INTO courses (course_name, course_description) VALUES ('Scala', 'Scala programming language');
INSERT INTO courses (course_name, course_description) VALUES ('Groovy', 'Groovy programming language');
INSERT INTO courses (course_name, course_description) VALUES ('Haskell', 'Haskell programming language');
INSERT INTO courses (course_name, course_description) VALUES ('Erlang', 'Erlang programming language');
INSERT INTO courses (course_name, course_description) VALUES ('Clojure', 'Clojure programming language');
INSERT INTO courses (course_name, course_description) VALUES ('F#', 'F# programming language');
INSERT INTO students (group_id, first_name, last_name) VALUES (1, 'John', 'Doe');
INSERT INTO students (group_id, first_name, last_name) VALUES (1, 'Jane', 'Doe');
INSERT INTO students (group_id, first_name, last_name) VALUES (2, 'John', 'Smith');
INSERT INTO students (group_id, first_name, last_name) VALUES (2, 'Jane', 'Smith');
INSERT INTO students (group_id, first_name, last_name) VALUES (3, 'Michael', 'Jackson');
INSERT INTO students (group_id, first_name, last_name) VALUES (3, 'Janet', 'Jackson');
INSERT INTO students (group_id, first_name, last_name) VALUES (4, 'Michael', 'Jordan');
INSERT INTO students (group_id, first_name, last_name) VALUES (4, 'Janet', 'Jordan');
INSERT INTO students (group_id, first_name, last_name) VALUES (5, 'Michael', 'Keaton');
INSERT INTO students (group_id, first_name, last_name) VALUES (5, 'Janet', 'Keaton');
INSERT INTO students (group_id, first_name, last_name) VALUES (6, 'Michael', 'Caine');
INSERT INTO students (group_id, first_name, last_name) VALUES (6, 'Janet', 'Caine');
INSERT INTO students (group_id, first_name, last_name) VALUES (7, 'Michael', 'Douglas');
INSERT INTO students (group_id, first_name, last_name) VALUES (7, 'Janet', 'Douglas');
INSERT INTO students (group_id, first_name, last_name) VALUES (8, 'Michael', 'Bolton');
INSERT INTO students (group_id, first_name, last_name) VALUES (8, 'Janet', 'Bolton');
INSERT INTO students (group_id, first_name, last_name) VALUES (9, 'Michael', 'Buble');
INSERT INTO students (group_id, first_name, last_name) VALUES (9, 'Janet', 'Buble');
INSERT INTO students (group_id, first_name, last_name) VALUES (10, 'Michael', 'Bolton');
INSERT INTO students (group_id, first_name, last_name) VALUES (10, 'Janet', 'Bolton');
INSERT INTO students (group_id, first_name, last_name) VALUES (1, 'Robert', 'De Niro');
INSERT INTO students (group_id, first_name, last_name) VALUES (1, 'Diane', 'Keaton');
INSERT INTO students (group_id, first_name, last_name) VALUES (2, 'Robert', 'Downey Jr.');
INSERT INTO students (group_id, first_name, last_name) VALUES (2, 'Chris', 'Evans');
INSERT INTO students (group_id, first_name, last_name) VALUES (3, 'Robert', 'Duvall');
INSERT INTO students (group_id, first_name, last_name) VALUES (3, 'Chris', 'Hemsworth');
INSERT INTO students (group_id, first_name, last_name) VALUES (4, 'Robert', 'Redford');
INSERT INTO students (group_id, first_name, last_name) VALUES (4, 'Chris', 'Pine');
INSERT INTO students (group_id, first_name, last_name) VALUES (5, 'Kevin', 'Costner');
INSERT INTO students (group_id, first_name, last_name) VALUES (5, 'Chris', 'Pratt');
INSERT INTO students (group_id, first_name, last_name) VALUES (6, 'Kevin', 'Spacey');
INSERT INTO students (group_id, first_name, last_name) VALUES (6, 'Luke', 'Skywalker');
INSERT INTO students (group_id, first_name, last_name) VALUES (7, 'Ja Ja', 'Binks');
INSERT INTO students (group_id, first_name, last_name) VALUES (7, 'Leia', 'Organa');
INSERT INTO students (group_id, first_name, last_name) VALUES (8, 'Han', 'Solo');
INSERT INTO students (group_id, first_name, last_name) VALUES (8, 'Darth', 'Vader');
INSERT INTO students (group_id, first_name, last_name) VALUES (9, 'Luke', 'Vader');
INSERT INTO students (group_id, first_name, last_name) VALUES (9, 'Darth', 'Skywalker');
INSERT INTO students (group_id, first_name, last_name) VALUES (10, 'John', 'Skywalker');
INSERT INTO students (group_id, first_name, last_name) VALUES (10, 'Darth', 'Solo');
INSERT INTO students_courses (student_id, course_id) VALUES (1, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (3, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (1, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (2, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (1, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (4, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (2, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (3, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (2, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (4, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (3, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (5, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (7, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (5, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (6, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (5, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (8, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (6, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (7, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (6, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (8, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (7, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (9, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (11, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (9, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (10, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (9, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (12, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (10, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (11, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (10, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (12, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (11, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (13, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (15, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (13, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (14, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (13, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (16, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (14, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (15, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (14, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (16, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (15, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (17, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (19, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (17, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (18, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (17, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (20, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (18, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (19, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (18, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (20, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (19, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (21, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (23, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (21, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (22, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (21, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (24, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (22, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (23, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (22, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (24, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (23, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (25, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (27, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (25, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (26, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (25, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (28, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (26, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (27, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (26, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (28, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (27, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (29, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (31, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (29, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (30, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (29, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (32, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (30, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (31, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (30, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (32, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (31, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (33, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (35, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (33, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (34, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (33, 5); 
INSERT INTO students_courses (student_id, course_id) VALUES (36, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (34, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (35, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (34, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (36, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (35, 10);
INSERT INTO students_courses (student_id, course_id) VALUES (37, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (39, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (37, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (38, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (37, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (38, 6);
INSERT INTO students_courses (student_id, course_id) VALUES (39, 8);
INSERT INTO students_courses (student_id, course_id) VALUES (38, 8);
