insert into groups (group_name) values ('Group 1');
insert into groups (group_name) values ('Group 2');
insert into groups (group_name) values ('Group 3');
insert into courses (course_name, course_description) values ('Course 1', 'Some description for course 1');
insert into courses (course_name, course_description) values ('Course 2', 'Some description for course 2');
insert into courses (course_name, course_description) values ('Course 3', 'Some description for course 3');
insert into students (group_id, first_name, last_name) values (1, 'Leia', 'Organa');
insert into students (group_id, first_name, last_name) values (1, 'Luke', 'Skywalker');
insert into students (group_id, first_name, last_name) values (1, 'Han', 'Solo');
insert into students (group_id, first_name, last_name) values (1, 'Padme', 'Amidala');
insert into students (group_id, first_name, last_name) values (2, 'Dart', 'Maul');
insert into students (group_id, first_name, last_name) values (2, 'Moff', 'Tarkin');
insert into students (group_id, first_name, last_name) values (2, 'Kylo', 'Ren');
insert into students (group_id, first_name, last_name) values (2, 'Count', 'Dooku');
insert into students (group_id, first_name, last_name) values (2, 'Dart', 'Vader');
insert into students (group_id, first_name, last_name) values (3, 'Jah Jah', 'Binks');
insert into students_courses (student_id, course_id) values (1, 1);
insert into students_courses (student_id, course_id) values (1, 3);
insert into students_courses (student_id, course_id) values (2, 1);
insert into students_courses (student_id, course_id) values (2, 2);
insert into students_courses (student_id, course_id) values (3, 2);
insert into students_courses (student_id, course_id) values (4, 1);
insert into students_courses (student_id, course_id) values (4, 2);
insert into students_courses (student_id, course_id) values (4, 3);
insert into students_courses (student_id, course_id) values (5, 1);
insert into students_courses (student_id, course_id) values (6, 2);
insert into students_courses (student_id, course_id) values (6, 3);
insert into students_courses (student_id, course_id) values (7, 3);
insert into students_courses (student_id, course_id) values (8, 2);
insert into students_courses (student_id, course_id) values (9, 1);
insert into students_courses (student_id, course_id) values (9, 2);
insert into students_courses (student_id, course_id) values (10, 1);
insert into students_courses (student_id, course_id) values (10, 3);
