INSERT INTO groups (group_name) VALUES ('Group 1');
INSERT INTO groups (group_name) VALUES ('Group 2');
INSERT INTO groups (group_name) VALUES ('Group 3');
INSERT INTO groups (group_name) VALUES ('Group 4');
INSERT INTO groups (group_name) VALUES ('Group 5');
INSERT INTO courses (course_name, course_description) VALUES ('Course 1', 'Description 1');
INSERT INTO courses (course_name, course_description) VALUES ('Course 2', 'Description 2');
INSERT INTO courses (course_name, course_description) VALUES ('Course 3', 'Description 3');
INSERT INTO courses (course_name, course_description) VALUES ('Course 4', 'Description 4');
INSERT INTO courses (course_name, course_description) VALUES ('Course 5', 'Description 5');
INSERT INTO students (group_id, first_name, last_name) VALUES (1, 'Student 1', 'Surname 1');
INSERT INTO students (group_id, first_name, last_name) VALUES (1, 'Student 2', 'Surname 2');
INSERT INTO students (group_id, first_name, last_name) VALUES (1, 'Student 3', 'Surname 3');
INSERT INTO students (group_id, first_name, last_name) VALUES (1, 'Student 4', 'Surname 4');
INSERT INTO students (group_id, first_name, last_name) VALUES (1, 'Student 5', 'Surname 5');
INSERT INTO students (group_id, first_name, last_name) VALUES (2, 'Student 6', 'Surname 6');
INSERT INTO students (group_id, first_name, last_name) VALUES (2, 'Student 7', 'Surname 7');
INSERT INTO students (group_id, first_name, last_name) VALUES (2, 'Student 8', 'Surname 8');
INSERT INTO students (group_id, first_name, last_name) VALUES (2, 'Student 9', 'Surname 9');
INSERT INTO students (group_id, first_name, last_name) VALUES (2, 'Student 10', 'Surname 10');
INSERT INTO students (group_id, first_name, last_name) VALUES (3, 'Student 11', 'Surname 11');
INSERT INTO students (group_id, first_name, last_name) VALUES (3, 'Student 12', 'Surname 12');
INSERT INTO students (group_id, first_name, last_name) VALUES (3, 'Student 13', 'Surname 13');
INSERT INTO students (group_id, first_name, last_name) VALUES (3, 'Student 14', 'Surname 14');
INSERT INTO students (group_id, first_name, last_name) VALUES (3, 'Student 15', 'Surname 15');
INSERT INTO students (group_id, first_name, last_name) VALUES (4, 'Student 16', 'Surname 16');
INSERT INTO students (group_id, first_name, last_name) VALUES (4, 'Student 17', 'Surname 17');
INSERT INTO students (group_id, first_name, last_name) VALUES (4, 'Student 18', 'Surname 18');
INSERT INTO students (group_id, first_name, last_name) VALUES (4, 'Student 19', 'Surname 19');
INSERT INTO students (group_id, first_name, last_name) VALUES (4, 'Student 20', 'Surname 20');
INSERT INTO students (group_id, first_name, last_name) VALUES (5, 'Student 21', 'Surname 21');
INSERT INTO students (group_id, first_name, last_name) VALUES (5, 'Student 22', 'Surname 22');
INSERT INTO students (group_id, first_name, last_name) VALUES (5, 'Student 23', 'Surname 23');
INSERT INTO students (group_id, first_name, last_name) VALUES (5, 'Student 24', 'Surname 24');
INSERT INTO students (group_id, first_name, last_name) VALUES (5, 'Student 25', 'Surname 25');
INSERT INTO students_courses (student_id, course_id) VALUES (1, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (1, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (1, 3);
INSERT INTO students_courses (student_id, course_id) VALUES (1, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (1, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (2, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (2, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (2, 3);
INSERT INTO students_courses (student_id, course_id) VALUES (2, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (2, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (3, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (3, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (3, 3);
INSERT INTO students_courses (student_id, course_id) VALUES (3, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (3, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (4, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (4, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (4, 3);
INSERT INTO students_courses (student_id, course_id) VALUES (4, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (4, 5);
INSERT INTO students_courses (student_id, course_id) VALUES (5, 1);
INSERT INTO students_courses (student_id, course_id) VALUES (5, 2);
INSERT INTO students_courses (student_id, course_id) VALUES (5, 3);
INSERT INTO students_courses (student_id, course_id) VALUES (5, 4);
INSERT INTO students_courses (student_id, course_id) VALUES (5, 5);
